rewardapp_postgresql:
    image: postgres
    container_name: rewardapp_postgresql
    volumes:
        - ./init.sql /docker-entrypoint-initdb.d/init.sql
    environment:
        - POSTGRES_MULTIPLE_DATABASES=userdb,rewarddb
        - POSTGRES_USER=coffeeapp
        - POSTGRES_PASSWORD=coffeeapp
        - POSTGRES_INITDB_ARGS= "-A md5"
    ports:
      - "5432:5432"